resources:
  - name: app_source
    type: git
    source:
      uri: https://github.com/Gidraff/bucketlist-react-app.git




jobs:
  - name: hello-there
    plan:
    - get: app_source
    - task: list_app_sources
      config:
        platform: linux
        inputs:
          - name: app_source
        image_resource:
          type: docker-image
          source: { repository: ubuntu }
        run:
          path: sh
          args:
            - -exc
            - |
              ls -R ./app_source
